[tool.poetry]
name = "word-analyser"
version = "0.1.0"
description = ""
authors = ["Mika Vilpas <mika.vilpas@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"
"ruamel.yaml" = "^0.15.37"
ensure = "^0.7.0"
nose = "^1.3"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
