[tool.poetry]
name = "word-analyser"
version = "0.1.0"
description = ""
authors = ["Mika Vilpas <mika.vilpas@gmail.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
